### ISSUE TITLE
Yaaic steals user attention and notification space by its "Connected to" notification

### ISSUE THREAD

**Issue by alvarezp** [pocmo/Yaaic#155]
Yaaic steals user attention and notification space by its "Connected to" notification, which is always set as Ongoing.

Many applications are doing this. As a result, real notifications get more difficult to see because they go all the way to the bottom of the list, outside of the screen.

My request is that either the icon gets removed or give an option to not show it, maybe some other user wants to have easy monitoring of the connection in an unstable network.

Thanks!

**Comment by pocmo** [comment]
Unfortunately this is a requirement by the Android system when a background service wants to run in the foreground:
http://developer.android.com/reference/android/app/Service.html#startForeground%28int,%20android.app.Notification%29

As we need a constant TCP connection in order to stay connected to the IRC network we need to run the service in the foreground. Otherwise Android might decide to kill it when needed - even though Android would restart the service the user would still be disconnected for some time.
